config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }


  resources :sizzlers do
    collection do
      get :nearby, action: :nearby_sizzlers
    end

    member do
      post :upload_photos
    end

    resources :bookings do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  resources :pages

  root to: "sizzlers#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :sizzler
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @sizzler = Sizzler.find(params[:sizzler_id])
    @booking = Booking.new
    @user = current_user
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to sizzler_booking_path(@booking.sizzler.id, @booking.id), notice: "Booking successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = current_user
    @bookings = Booking.all
    # @booking = Booking.find(params[:id])
    # @sizzler = @booking.sizzler
  end

  def destroy
    @booking = Booking.find(params[:id])
    @sizzler = @booking.sizzler
    @booking.destroy
    redirect_to sizzler_booking_path(@sizzler)
  end

  def accept
    @sizzler = Sizzler.find(params[:sizzler_id])
    @booking = Booking.find(params[:id])
    @booking.update(accepted: "accepted")
    redirect_to page_path(@sizzler)
  end

  def decline
    @sizzler = Sizzler.find(params[:sizzler_id])
    @booking = Booking.find(params[:id])
    @booking.update(accepted: "declined")
    redirect_to page_path(@sizzler)
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :sizzler_id, :user_id, :accepted)
  end

end

app/views/bookings/index.html.erb
<!--<h1>Hello</h1>-->
<h1>All bookings for <%= @user.name %></h1>

<% @bookings.each do |booking| %>
  <div style="display: block;">
    <%= booking.user.name %>
    <%= booking.date %>
    <%= booking.sizzler.title %>
  </div>
  <%= link_to "Delete", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>

app/views/bookings/new.html.erb
<div class="bookings-container">
  <h1>When would you like to Sizzle?</h1>

  <%= simple_form_for([ @sizzler, @booking ]) do |f| %>
    <%= f.input :date,
          as: :string,
          input_html: { data: { controller: "datepicker" } } %>
    <%= f.hidden_field :sizzler_id, value: @sizzler.id %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :accepted, value: "pending" %>
    <%= f.submit "Book Sizzler", class: "btn-card-date" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="bookings-container-show">
  <h1>All <%= @user.name %>'s bookings </h1>
  <div class="bookings-list">
      <% @bookings.each do |booking| %>
      <div class="booking-item-container">
        <div class="booking-item">
          <p><strong>Booking by:</strong> <%= booking.user.name%></p>
          <p><strong>Date: </strong><%= booking.date.try(:strftime, "%Y-%m-%d") %></p>
          <p><strong>For:</strong> <%= booking.sizzler.title %></p>
        </div>
        <div class="buttons">
          <%#= link_to "Delete", sizzler_booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <% if booking.accepted == "pending" %>
            <button class="btn-pending"><%= booking.accepted %></button>
          <% elsif booking.accepted == "accepted" %>
            <button class="btn-accepted"><%= booking.accepted %></button>
          <% else %>
            <button class="btn-decline"><%= booking.accepted %></button>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>