config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }


  resources :sizzlers do
    collection do
      get :nearby, action: :nearby_sizzlers
    end

    member do
      post :upload_photos
    end

    resources :bookings do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  resources :pages

  root to: "sizzlers#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/index.html.erb
<div class="bookings-container">
  <div class="inner-container">
    <h1>My Sizzles</h1>
    <div class="sizzle-card">
      <% @user.owned_sizzlers.each do |sizzle| %>
      <div class="sizzle-item">
        <div class="left">
          <strong><%= sizzle.title %></strong>
          <%= sizzle.price %>
        </div>
        <div class="link-container">
          <%= link_to "View bookings", page_path(sizzle.id), class: "btn-card-hire" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<div class="sizzle-account-container">
  <h1 class="header">Bookings for <%= @sizzler.title %></h1>

  <% @bookings.each do | booking | %>
  <div class="date-container">
    <div class="date-item">
      <%= booking.user.name %>
      <br>
      <%= booking.date %>
    </div>
    <div class="link-container">
      <% if booking.accepted == "accepted" || booking.accepted == "declined" %>
        <p><%= booking.accepted %></p>
      <% else %>
        <%= form_with(model: booking, url: accept_sizzler_booking_path(@sizzler, booking), method: :patch) do |f| %>
          <%= f.submit "Accept" %>
        <% end %>
        <%= form_with(model: booking, url: decline_sizzler_booking_path(@sizzler, booking), method: :patch) do |f| %>
          <%= f.submit "Decline" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>